
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataProvider", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:50041/DataProvider.svc?wsdl")
public class DataProvider
    extends Service
{

    private final static URL DATAPROVIDER_WSDL_LOCATION;
    private final static WebServiceException DATAPROVIDER_EXCEPTION;
    private final static QName DATAPROVIDER_QNAME = new QName("http://tempuri.org/", "DataProvider");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50041/DataProvider.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAPROVIDER_WSDL_LOCATION = url;
        DATAPROVIDER_EXCEPTION = e;
    }

    public DataProvider() {
        super(__getWsdlLocation(), DATAPROVIDER_QNAME);
    }

    public DataProvider(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAPROVIDER_QNAME, features);
    }

    public DataProvider(URL wsdlLocation) {
        super(wsdlLocation, DATAPROVIDER_QNAME);
    }

    public DataProvider(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAPROVIDER_QNAME, features);
    }

    public DataProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataProvider(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDataProvider
     */
    @WebEndpoint(name = "BasicHttpBinding_IDataProvider")
    public IDataProvider getBasicHttpBindingIDataProvider() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDataProvider"), IDataProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDataProvider
     */
    @WebEndpoint(name = "BasicHttpBinding_IDataProvider")
    public IDataProvider getBasicHttpBindingIDataProvider(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDataProvider"), IDataProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAPROVIDER_EXCEPTION!= null) {
            throw DATAPROVIDER_EXCEPTION;
        }
        return DATAPROVIDER_WSDL_LOCATION;
    }

}
